// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuTRb3DbrF2UrJaWtdrOSQkF_Fp6WzmM4',
    appId: '1:555276548646:web:b7071c673015c81c62c4e7',
    messagingSenderId: '555276548646',
    projectId: 'fyp-bin-app',
    authDomain: 'fyp-bin-app.firebaseapp.com',
    storageBucket: 'fyp-bin-app.firebasestorage.app',
    measurementId: 'G-7BTV1920ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA99rgTW1XbXU4e_aAeO4GuoFSBNaM-y60',
    appId: '1:555276548646:android:951f9fc2e3b6183b62c4e7',
    messagingSenderId: '555276548646',
    projectId: 'fyp-bin-app',
    storageBucket: 'fyp-bin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaOEe5bkFBKsnxzv_nNvIAKpa14Yfcag8',
    appId: '1:555276548646:ios:375a01b95810de2862c4e7',
    messagingSenderId: '555276548646',
    projectId: 'fyp-bin-app',
    storageBucket: 'fyp-bin-app.firebasestorage.app',
    iosBundleId: 'com.example.iotBinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaOEe5bkFBKsnxzv_nNvIAKpa14Yfcag8',
    appId: '1:555276548646:ios:375a01b95810de2862c4e7',
    messagingSenderId: '555276548646',
    projectId: 'fyp-bin-app',
    storageBucket: 'fyp-bin-app.firebasestorage.app',
    iosBundleId: 'com.example.iotBinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuTRb3DbrF2UrJaWtdrOSQkF_Fp6WzmM4',
    appId: '1:555276548646:web:adae9919c3cf2bea62c4e7',
    messagingSenderId: '555276548646',
    projectId: 'fyp-bin-app',
    authDomain: 'fyp-bin-app.firebaseapp.com',
    storageBucket: 'fyp-bin-app.firebasestorage.app',
    measurementId: 'G-GEBFVMYW2Q',
  );
}
